// Tailwind build config for LabUI (see base.html and jfr/web/themes.py).
// Rebuild after editing templates:  npm run build:css
const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const ramp = (name) =>
  Object.fromEntries(STEPS.map((s) => [s, `rgb(var(--c-${name}-${s}) / <alpha-value>)`]));

module.exports = {
  darkMode: "class",
  content: [
    "./submission_strategy/jfr/web/templates/**/*.html",
    "./submission_strategy/jfr/web/static/**/*.js",
  ],
  theme: {
    extend: {
      // Font sets are CSS variables too (html[data-font="…"] in themes.css).
      fontFamily: {
        sans: ["var(--font-sans)"],
        display: ["var(--font-display)"],
        serif: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
      },
      // Colours are CSS variables ("R G B" channels) defined per palette in
      // static/themes.css — generated by submission_strategy/jfr/web/themes.py —
      // so utilities follow the selected theme and keep alpha modifiers.
      colors: {
        ink: ramp("ink"),      // paper-and-ink neutrals
        brand: ramp("brand"),  // the accent ("signal")
        data: ramp("data"),    // secondary — measurements, your own text
        live: ramp("live"),    // streaming / running
      },
      boxShadow: {
        soft: "0 1px 0 rgba(23,21,18,0.04), 0 1px 2px rgba(23,21,18,0.04)",
        "soft-dark": "0 1px 0 rgba(0,0,0,0.4), 0 1px 2px rgba(0,0,0,0.3)",
        lift: "0 2px 4px rgba(23,21,18,0.05), 0 12px 28px -14px rgba(23,21,18,0.22)",
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.22, 1, 0.36, 1)",
      },
    },
  },
};
